"""
models/response_generator.py
──────────────────────────────
Response generation is now handled by OpenRouter (Gemma free model) in app.py.

This file is kept for backwards-compatibility with train.py imports.
It provides a no-op ResponseGenerator so train.py can still call rg.train()
and build the response index (used only as a corpus reference now — the
actual response comes from the AI API, not TF-IDF retrieval).
"""

import logging
import joblib
from pathlib import Path

log      = logging.getLogger(__name__)
SAVE_DIR = Path(__file__).parent / "saved" / "response"
SAVE_DIR.mkdir(parents=True, exist_ok=True)


class ResponseGenerator:
    """
    Lightweight corpus indexer kept for train.py compatibility.
    Actual responses are generated by OpenRouter in app.py — this class
    just saves the training corpus so it can be inspected or retrained.
    """

    def __init__(self):
        self._corpus : list[dict] = []
        self._trained = False

    def train(self, rows: list[dict]):
        log.info(f"  Response: indexing {len(rows)} pairs (corpus only — AI handles generation)")
        self._corpus  = rows
        self._trained = True
        self._save()
        log.info(f"  Corpus saved ({len(rows)} entries)")

    def _save(self):
        joblib.dump(self._corpus, SAVE_DIR / "corpus.pkl")

    def load(self):
        path = SAVE_DIR / "corpus.pkl"
        if path.exists():
            self._corpus  = joblib.load(path)
            self._trained = True

    def is_saved(self):
        return (SAVE_DIR / "corpus.pkl").exists()

    def generate(self, prompt: str, intent: str = "general", max_words: int = 320) -> dict:
        """
        Fallback only — called if app.py somehow uses this class directly.
        In normal operation, app.py calls OpenRouter directly.
        """
        return {
            "response": (
                "AI response engine (OpenRouter) is handling this request. "
                "If you see this message, check that app.py is running correctly."
            ),
            "retrieval_score": 0.0,
            "sources_used":    0,
        }